### PR TITLE
Increased log level on messages that should be errors

### LINKED ISSUE #128: No feedback when config write fails
Cuttlefish does a great job of explaining errors when they happen while generating app.config and vm.args in memory. The problem here, is that after that phase, if it can't actually write out those files to disk it give the ol' cryptic "failed to generate config with cuttlefish". It could be worse, that message used to end with "there should be logs"

### PR DESCRIPTION
**Pull request by joedevivo**
Fixes #128 

```
➜  riak git:(develop) ✗ sudo chmod -R 644 data 
➜  riak git:(develop) ✗ ./bin/riak config generate         
15:52:03.672 [error] Unable to create directory ./data/generated.configs - eacces.  Please check permissions.
```

### CODE REVIEW

File: src/cuttlefish_escript.erl [hunk 1]
```diff
@@ -325,9 +325,15 @@ engage_cuttlefish(ParsedArgs) ->
             FinalAppConfig = proplists:delete(vm_args, FinalConfig),
             FinalVMArgs = cuttlefish_vmargs:stringify(proplists:get_value(vm_args, FinalConfig)),
 
-            ok = file:write_file(Destination,io_lib:fwrite("~p.\n",[FinalAppConfig])),
-            ok = file:write_file(DestinationVMArgs, io_lib:fwrite(string:join(FinalVMArgs, "\n"), [])),
-            {Destination, DestinationVMArgs}
+            case { file:write_file(Destination, io_lib:fwrite("~p.\n",[FinalAppConfig])),
+                   file:write_file(DestinationVMArgs, io_lib:fwrite(string:join(FinalVMArgs, "\n"), []))} of
```
Comment (seancribbs) [inline src/cuttlefish_escript.erl]: The `io_lib:fwrite` is unnecessary here because you aren't formatting anything.

File: src/cuttlefish_escript.erl [hunk 2]
```diff
@@ -325,9 +325,15 @@ engage_cuttlefish(ParsedArgs) ->
...
+                {ok, ok} ->
+                    {Destination, DestinationVMArgs};
+                _ ->
+                    lager:error("Unable to write ~s and/or ~s.  Please check permissions.", [Destination, DestinationVMArgs]),
```
Comment (seancribbs) [inline src/cuttlefish_escript.erl]: The actual errors might be nice to match here, and can be formatted such that they aren't just `posix()` atoms. See the docs for `file:format_error/1`.

Comment (seancribbs) [inline src/cuttlefish_escript.erl]: Suggestion:

``` erlang
{Err1, Err2} ->
    lager:error("Unable to write ~s and/or ~s.  Please check permissions.", [Destination, DestinationVMArgs]),
    maybe_log_file_error(Destination, Err1),
    maybe_log_file_error(DestinationVMArgs, Err2)
    ok;
%% [snip]

maybe_log_file_error(_, ok) -> ok;
maybe_log_file_error(File, {error, Reason}) ->
    lager:error("~s: ~s", [File, file:format_error(Reason)]),
    ok.
```

**Comment by seancribbs** [comment]
- [x] eunit
- [x] dialyzer
- [x] xref
- [x] manual testing

File: src/cuttlefish_escript.erl [hunk 3]
```diff
@@ -270,7 +270,7 @@ engage_cuttlefish(ParsedArgs) ->
                 ok ->
                     DP;
                 {error, E} ->
-                    lager:info("Unable to create directory ~s - ~p.  Please check permissions.", [DP, E]),
+                    lager:error("Unable to create directory ~s - ~p.  Please check permissions.", [DP, E]),
```
Comment (seancribbs) [inline src/cuttlefish_escript.erl]: Like below, logging why the directory could not be created would be helpful, rather than just making the user guess.

**Comment by seancribbs** [comment]
This works as intended, passes automated and manual tests, etc, but I'd really love to see the output format and information be better before this merges.

**Comment by joedevivo** [comment]
```
➜  Desktop  chmod 644 cantwrite
➜  cuttlefish git:(jd-file-write-error-handling) ✗ ./cuttlefish -e ~/dev/basho/riak/rel/riak/etc -s ~/dev/basho/riak/rel/riak/lib -d ~/Desktop/cantwrite -c ~/dev/basho/riak/rel/riak/etc/riak.conf 
08:52:49.454 [error] Error writing /Users/joe/Desktop/cantwrite/app.2014.02.27.08.52.49.config: permission denied
08:52:49.454 [error] Error writing /Users/joe/Desktop/cantwrite/vm.2014.02.27.08.52.49.args: permission denied
➜  cuttlefish git:(jd-file-write-error-handling) ✗ ./cuttlefish -e ~/dev/basho/riak/rel/riak/etc -s ~/dev/basho/riak/rel/riak/lib -d ~/Desktop/cantwrite/cantsub -c ~/dev/basho/riak/rel/riak/etc/riak.conf
08:55:04.136 [error] Unable to create directory /Users/joe/Desktop/cantwrite/cantsub - "permission denied".  Please check permissions.
```

**Comment by seancribbs** [comment]
r+
:+1: 5aeb970
